language: node_js

node_js:
  - 10

script:
  - yarn test --config video=true --record --key $CYPRESS_DASHBOARD_KEY

branches:
  except:
    - /^issue\-/

cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
